name: zae_labeler
description: "ZAE Labeler - A Flutter-based multi-modal data labeling tool supporting classification and segmentation."
publish_to: 'none'
version: 1.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  uuid: ^3.0.6
  file_picker: ^5.2.5
  path_provider: ^2.0.15
  fl_chart: ^0.55.2
  archive: ^3.3.2
  permission_handler: ^10.2.0
  share_plus: ^6.3.0
  path: ^1.8.3
  cupertino_icons: ^1.0.2
  mockito: ^5.4.4
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/zaevicon.png
