name: zae_labeler
description: "ZAE Labeler - A Flutter-based multi-modal data labeling tool supporting classification and segmentation."
publish_to: 'none'
version: 1.1.1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  uuid: ^4.3.3
  file_picker: ^10.3.2
  path_provider: ^2.0.15
  fl_chart: ^1.0.0
  archive: ^4.0.7
  permission_handler: ^12.0.1
  share_plus: ^11.1.0
  path: ^1.8.3
  cupertino_icons: ^1.0.2
  mockito: ^5.4.4
  shimmer: ^3.0.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^7.1.1
  cloud_firestore: ^6.0.0
  kakao_flutter_sdk_user: ^1.9.2
  url_launcher: ^6.3.0
  lottie: ^3.3.1
  universal_html: ^2.2.4
  # web: ^0.5.0 # Uncomment if you need web support
  win32: ^5.0.0
  firebase_storage: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/zaevicon.png
    - assets/zae-splash.json
    - assets/zae-splash_15_frame.gif
    - assets/zae-splash_24_frame.gif
    - assets/zae-splash2.gif
    - assets/zae-splash2.webm
