name: zae_labeler
description: "ZAE Labeler - A Flutter-based multi-modal data labeling tool supporting classification and segmentation."
publish_to: 'none'
version: 1.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  uuid: ^3.0.6
  file_picker: ^5.2.5
  path_provider: ^2.0.15
  fl_chart: ^0.55.2
  archive: ^3.3.2
  permission_handler: ^10.2.0
  share_plus: ^6.3.0
  path: ^1.8.3
  cupertino_icons: ^1.0.2
  mockito: ^5.4.4
  shimmer: ^3.0.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.8
  kakao_flutter_sdk_user: ^1.9.2
  url_launcher: ^6.3.0
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/zaevicon.png
    - assets/zae-splash.json
    - assets/zae-splash_15_frame.gif
    - assets/zae-splash_24_frame.gif
    - assets/zae-splash2.gif
    - assets/zae-splash2.webm
