name: Dart

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Use the latest Flutter version to ensure compatibility with Dart >=3.2.3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable' # 'stable' 채널의 최신 버전 사용

      - name: Flutter version 확인
        run: flutter --version

      - name: Install dependencies
        working-directory: ./zae_labeler
        run: flutter pub get

      - name: Analyze project source
        working-directory: ./zae_labeler
        run: flutter analyze

      - name: Run tests
        working-directory: ./zae_labeler
        run: flutter test
