name: Dart

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [3.24, stable]

    steps:
      - uses: actions/checkout@v4

      # Use the latest Flutter version to ensure compatibility with Dart >=3.2.3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Flutter version 확인
        run: flutter --version

      - name: Install dependencies
        working-directory: ./zae_labeler
        run: flutter pub get

      - name: Analyze project source
        working-directory: ./zae_labeler
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Run tests (excluding web-only)
        working-directory: ./zae_labeler
        run: flutter test

      
  test-web:
    runs-on: ubuntu-latest
    name: Web Tests (Chrome)
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
      - name: Enable web
        run: flutter config --enable-web
      - name: Install dependencies
        working-directory: ./zae_labeler
        run: flutter pub get
      - name: Run tests for web (Chrome)
        working-directory: ./zae_labeler
        run: flutter test --platform=chrome
        
