name: Dart

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Use Flutter instead of Dart
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0' # 원하는 Flutter 버전 지정

      - name: Install dependencies
        working-directory: ./zae_labeler
        run: flutter pub get

      - name: Analyze project source
        working-directory: ./zae_labeler
        run: flutter analyze

      - name: Run tests
        working-directory: ./zae_labeler
        run: flutter test
