name: Dart

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [3.24, stable]

    steps:
      - uses: actions/checkout@v4

      # Use the latest Flutter version to ensure compatibility with Dart >=3.2.3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Flutter version 확인
        run: flutter --version

      - name: Install dependencies
        working-directory: ./zae_labeler
        run: flutter pub get

      - name: Analyze project source
        working-directory: ./zae_labeler
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Run tests (excluding web-only)
        working-directory: ./zae_labeler
        run: flutter test --exclude-tags=web-only
      
      - name: Run web-only tests
        run: flutter test --tags=web-only
      