name: Test and Deploy Documentation

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        dart: ["2.17.0", "2.18.0", "stable"] # 테스트할 Dart SDK 버전
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v2
        with:
          sdk: ${{ matrix.dart }}

      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v1.5.0
        with:
          channel: stable
      
      - name: Check Flutter environment
        run: flutter doctor -v

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./zae_labeler
        run: flutter pub get

      - name: Build web
        working-directory: ./zae_labeler
        run: flutter build web

      - name: Deploy to GitHub Pages
        if: matrix.os == 'ubuntu-latest' && matrix.dart == 'stable'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_LABLER }}
          publish_branch: docs
          publish_dir: zae_labeler/build/web
